# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-13 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnUrl', '0002_auto_20170813_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anasurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
